language: r
sudo: true
warnings_are_errors: true
cache: packages
r_github_packages:
  - rich-iannone/DiagrammeR
before_install:
  - chmod 755 ./.push_gh_pages.sh
  - wget https://download.microsoft.com/download/2/E/5/2E58F097-805C-4AB8-9FC6-71288AB4409D/msodbcsql-13.0.0.0.tar.gz -P ..
  - tar xvzf ../msodbcsql-13.0.0.0.tar.gz -C ..
  - ../msodbcsql-13.0.0.0/build_dm.sh --accept-warning
  - cd ../tmp/unixODBC.32090.16651.27638/unixODBC-2.3.1; make install
after_success:
  - ./.push_gh_pages.sh
