language: r
warnings_are_errors: true
cache: packages
apt_packages:
  - unixodbc
r_github_packages:
  - rich-iannone/DiagrammeR
before_install:
  - chmod 755 ./.push_gh_pages.sh
after_success: ./.push_gh_pages.sh
