language: r
sudo: true
warnings_are_errors: true
cache: packages
r_github_packages:
  - rich-iannone/DiagrammeR
before_install:
  - chmod 755 ./.push_gh_pages.sh
  - sudo bash Driver.sh
  - cd $TRAVIS_BUILD_DIR
  - odbcinst -q -d

after_success:
  - ./.push_gh_pages.sh
