---
title: "Getting started with R"
author: "Steph Locke"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document: 
    code_folding: show
    number_sections: yes
    toc: yes
    toc_float: true
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{Getting started with R}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

[Home](index.html) | [Prev](RMicrosoft.html) | [Next]()

# The software {.tabset}
<!-- Source: github.com/stephlocke/Rtraining/inst/handouts/infrastructure/setting-up-a-windows-r-machine -->
This section outlines installation instructions for getting up to speed

## R
 * Download latest base R exe file from [cran.rstudio.com](http://cran.rstudio.com/)
 * Also download Rtools latest exe (if using Windows)
 * Install R then Rtools - if 64bit, install both 32 and 64 as it saves you hassle with other drivers

## Git
 * Download latest git version from [msysgit.github.io](https://msysgit.github.io/)
 * Install
 * Open up command-prompt
     + Run `git config --global user.name="Your name"`
     + Run `git config --global user.email="email@addre.ss"`

## Rstudio
 * Go to [rstudio.com](http://www.rstudio.com/products/rstudio/download/)
 * Select correct install file for your PC, and install
 * Open Rstudio
 * Go to Tools > Global Options and set Rstudio to point at the location of your git.exe file
 * Restart Rstudio
     + If you don't automatically get the Git pane (top RHS) then Create a New Project and tick the source control checkbox
 * Go to the Packages area (bottom RHS) and select Install. Install `devtools`

# Navigating Rstudio {.tabset}
This section provides a simple reference for working with Rstudio.

# The RMSFTDP package {.tabset}
This section introduces the package R in the Microsoft Data Platform, or **RMSFTDP** for short.

## Purpose
## Get it 
 * Open RStudio
 * Get the project from source control by going to New Project in Rstudio, selecting from version control, and pasting in the URL `https://github.com/stephlocke/RMSFTDP.git
 * Run `devtools::install()` to install the package

## Contents
 * `vignettes/` - use `devtools::build_vignettes()` to generate a local copy of the training materials

# R Syntax {.tabset}

<!-- Source: github.com/stephlocke/Rtraining/inst/handouts/fundamentals/syntax -->
## Basic operators

Action | Operator | Example
------------- | ------------- | -------------
Subtract | - | `5 - 4` = `r 5 - 4`
Add | + | `5 + 4` = `r 5 + 4`
Multiply | * | `5 * 4` = `r 5 * 4`
Divide | / | `5 / 4` = `r 5 / 4`
Raise to the power | ^ | `5 ^ 4` = `r 5 ^ 4`
Modulus | %% | `10 %% 4` = `r 10 %% 4`
Absolute remainder | %/% | `9 %/% 4` = `r 9 %/% 4`
Basic sequence | : | `sum(1:3)` = `r sum(1:3)`

## Comparison operators

Action | Operator | Example
------------- | ------------- | -------------
Less than | < | `5 < 5` = `r 5 < 5`
Less than or equal to | <= | `5 <= 5` = `r 5 <= 5`
Greater than | > | `5 > 5` = `r 5 > 5`
Greater than or equal to | >= | `5 >= 5` = `r 5 >= 5`
Exactly equal | == | `(0.5 - 0.3) == (0.3 - 0.1)` is `r (0.5 - 0.3) == (0.3 - 0.1)`, 2 == 2 is `r 2==2`
Not equal | != | `(0.5 - 0.3) != (0.3 - 0.1)` is `r (0.5 - 0.3) != (0.3 - 0.1)`, 2 != 2 is `r 2!=2`
Equal | all.equal() | `all.equal(0.5 - 0.3,0.3 - 0.1)` is `r all.equal(0.5 - 0.3,0.3 - 0.1)`

## States

States | Representation  
------------- | -------------
True | `TRUE` `1`
False | `FALSE` `0`
Empty | `NULL`
Unknown | `NA`
Not a number e.g. `0/0`| `NaN`
Infinite e.g. `1/0` | `Inf`

## Logical operators

Action | Operator | Example
------------- | ------------- | -------------
Not | ! | `!TRUE` is `r !TRUE`
And | & | `TRUE & FALSE` is `r TRUE & FALSE`, `c(TRUE,TRUE) & c(FALSE,TRUE)` is `r c(TRUE,TRUE) & c(FALSE,TRUE)`
Or | `|` | `TRUE | FALSE` is `r TRUE | FALSE`, `c(TRUE,FALSE) | c(FALSE,FALSE)` is `r c(TRUE,FALSE) | c(FALSE,FALSE)`
Xor | xor() | `xor(TRUE,FALSE)` is `r xor(TRUE,FALSE)`
Bitwise And | && | `c(TRUE,TRUE) && c(FALSE,TRUE)` is `r c(TRUE,TRUE) && c(FALSE,TRUE)`
Bitwise Or | `||` | `c(TRUE,FALSE) || c(FALSE,FALSE)` is `r c(TRUE,FALSE) || c(FALSE,FALSE)`
In | %in% | `"Red" %in% c("Blue","Red")` is `r  "Red" %in% c("Blue","Red")`
Not in | !( x %in% y)  | `!("Red" %in% c("Blue","Red"))` = `r !("Red" %in% c("Blue","Red"))`



## Control constructs

Type | Implementation | Example
------------- | ------------- | -------------
If | if(condition) {dosomething} | `if(TRUE) { 2 }` is `r if(TRUE) { 2 }`
If else | if(condition) {do something} else {do something different} or ifelse(condition, do something, do something else) | `if(FALSE) { 2 } else { 3 }` is `r if(FALSE) { 2 } else { 3 }` `ifelse(FALSE, 2, 3)` is `r ifelse(FALSE, 2, 3)`
For loop | for(i in seq) {dosomething} or foreach(i=1:3) %do% {something} | `for(i in 1:3) {print(i)}` is `r paste0(1:3)` 
While loop | while(condition) {do something } | `a<-0 ; while(a<3){a<-a+1} ; a` is `r a<-0 ; while(a<3){a<-a+1} ; a`
Switch | switch(value, ...) | `switch(2, "a", "b")` is `r switch(2, "a", "b")`
Case | memisc::cases(...) | `cases("pi<3"=pi<3, "pi=3"=pi==3,"pi>3"=pi>3)` is `r memisc::cases("pi<3"=pi<3, "pi=3"=pi==3,"pi>3"=pi>3)`

> NB: If you find yourself using a loop, there's probably a better, faster solution

## Assignment operators

Action | Operator | Example
------------- | ------------- | -------------
Create / update a variable | <- | `a <- 10`

> NB: There are others you could use, but this is the best practice

## Accessors

Action | Operator | Example
------------- | ------------- | -------------
Use public function from package | :: | `memisc::cases()`
Use private function from package | ::: | `optiRum:::pounds_format()`
Get a component e.g a data.frame column | $ | `iris$Sepal.Length`
Extract a property from a class | `@` | *Won't be used in this course*
Refer to positions in a data.frame or vector | [ ] | `iris[5:10,1]`
Refer to item in a list | [[ ]] | `list(iris=iris,mtcars=mtcars)[["iris"]]`

## Meta-operators

Action | Operator | Example
------------- | ------------- | -------------
Comment | # | `# This is my comment`
Help | ? | `?data.table`
Identifier | \` |  `` `1`<-2``

# R Data structures
# R Functions

# Exercises

-------
[Home](index.html) | [Prev](RMicrosoft.html) | [Next]()
